name: Build & Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: skygrade
  REGION: us-central1
  GAR_REPO: us-central1-docker

jobs:
  build-and-deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.DEPLOY_SA }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build & push images (multi-arch)
        run: |
          # Build agent
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/agent:latest \
            -f apps/open-swe/Dockerfile . --push

          # Build agent-v2
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/agent-v2:latest \
            -f apps/open-swe-v2/Dockerfile . --push

          # Build web UI
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/web:latest \
            -f apps/web/Dockerfile . --push

      - name: Deploy to Cloud Run (agent)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: agent
          image: $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/agent:latest
          region: $REGION
          env_vars: |-
            PORT=2024
          secrets: open-swe-agent-env
          min_instances: 0
          max_instances: 25
          cpu: 2
          memory: 4Gi

      - name: Deploy to Cloud Run (agent-v2)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: agent-v2
          image: $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/agent-v2:latest
          region: $REGION
          env_vars: |-
            PORT=2025
          secrets: open-swe-agent-v2-env
          min_instances: 0
          max_instances: 25
          cpu: 2
          memory: 4Gi

      - name: Deploy to Cloud Run (web)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: web-ui
          image: $REGION-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/web:latest
          region: $REGION
          env_vars: |-
            PORT=8080
          secrets: open-swe-web-env
          min_instances: 0
          max_instances: 10
          cpu: 1
          memory: 1Gi
